// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GenerateIdentity():Promise<main.Identity>;

export function SignMessage(arg1:string,arg2:string):Promise<string>;

export function VerifyMessage(arg1:string,arg2:string,arg3:string):Promise<boolean>;
