// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddLocalPost(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddLocalPost'](arg1, arg2, arg3);
}

export function AddTrustedAdmin(arg1, arg2) {
  return window['go']['main']['App']['AddTrustedAdmin'](arg1, arg2);
}

export function ApplyShadowBan(arg1, arg2, arg3) {
  return window['go']['main']['App']['ApplyShadowBan'](arg1, arg2, arg3);
}

export function ApplyUnban(arg1, arg2, arg3) {
  return window['go']['main']['App']['ApplyUnban'](arg1, arg2, arg3);
}

export function ConnectPeer(arg1) {
  return window['go']['main']['App']['ConnectPeer'](arg1);
}

export function GenerateIdentity() {
  return window['go']['main']['App']['GenerateIdentity']();
}

export function GetFeed() {
  return window['go']['main']['App']['GetFeed']();
}

export function GetIdentityState() {
  return window['go']['main']['App']['GetIdentityState']();
}

export function GetModerationState() {
  return window['go']['main']['App']['GetModerationState']();
}

export function GetP2PStatus() {
  return window['go']['main']['App']['GetP2PStatus']();
}

export function GetPrivateFeed() {
  return window['go']['main']['App']['GetPrivateFeed']();
}

export function GetStorageUsage() {
  return window['go']['main']['App']['GetStorageUsage']();
}

export function GetTrustedAdmins() {
  return window['go']['main']['App']['GetTrustedAdmins']();
}

export function ImportIdentityFromMnemonic(arg1) {
  return window['go']['main']['App']['ImportIdentityFromMnemonic'](arg1);
}

export function LoadSavedIdentity() {
  return window['go']['main']['App']['LoadSavedIdentity']();
}

export function ProcessIncomingMessage(arg1) {
  return window['go']['main']['App']['ProcessIncomingMessage'](arg1);
}

export function PublishPost(arg1, arg2) {
  return window['go']['main']['App']['PublishPost'](arg1, arg2);
}

export function PublishShadowBan(arg1, arg2, arg3) {
  return window['go']['main']['App']['PublishShadowBan'](arg1, arg2, arg3);
}

export function PublishUnban(arg1, arg2, arg3) {
  return window['go']['main']['App']['PublishUnban'](arg1, arg2, arg3);
}

export function SetDatabasePath(arg1) {
  return window['go']['main']['App']['SetDatabasePath'](arg1);
}

export function SignMessage(arg1, arg2) {
  return window['go']['main']['App']['SignMessage'](arg1, arg2);
}

export function StartP2P(arg1, arg2) {
  return window['go']['main']['App']['StartP2P'](arg1, arg2);
}

export function StopP2P() {
  return window['go']['main']['App']['StopP2P']();
}

export function VerifyMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['VerifyMessage'](arg1, arg2, arg3);
}
