// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddLocalComment(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddLocalComment'](arg1, arg2, arg3, arg4);
}

export function AddLocalPostStructured(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddLocalPostStructured'](arg1, arg2, arg3, arg4);
}

export function AddLocalPostStructuredToSub(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddLocalPostStructuredToSub'](arg1, arg2, arg3, arg4, arg5);
}

export function AddLocalPostWithImageToSub(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['AddLocalPostWithImageToSub'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function AddTrustedAdmin(arg1, arg2) {
  return window['go']['main']['App']['AddTrustedAdmin'](arg1, arg2);
}

export function ApplyShadowBan(arg1, arg2, arg3) {
  return window['go']['main']['App']['ApplyShadowBan'](arg1, arg2, arg3);
}

export function ApplyUnban(arg1, arg2, arg3) {
  return window['go']['main']['App']['ApplyUnban'](arg1, arg2, arg3);
}

export function ConnectPeer(arg1) {
  return window['go']['main']['App']['ConnectPeer'](arg1);
}

export function CreateSub(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateSub'](arg1, arg2, arg3);
}

export function GenerateIdentity() {
  return window['go']['main']['App']['GenerateIdentity']();
}

export function GetAntiEntropyStats() {
  return window['go']['main']['App']['GetAntiEntropyStats']();
}

export function GetCommentsByPost(arg1) {
  return window['go']['main']['App']['GetCommentsByPost'](arg1);
}

export function GetFeed() {
  return window['go']['main']['App']['GetFeed']();
}

export function GetFeedBySub(arg1) {
  return window['go']['main']['App']['GetFeedBySub'](arg1);
}

export function GetFeedBySubSorted(arg1, arg2) {
  return window['go']['main']['App']['GetFeedBySubSorted'](arg1, arg2);
}

export function GetFeedIndexBySubSorted(arg1, arg2) {
  return window['go']['main']['App']['GetFeedIndexBySubSorted'](arg1, arg2);
}

export function GetFeedStream(arg1) {
  return window['go']['main']['App']['GetFeedStream'](arg1);
}

export function GetFeedStreamWithStrategy(arg1, arg2) {
  return window['go']['main']['App']['GetFeedStreamWithStrategy'](arg1, arg2);
}

export function GetGovernancePolicy() {
  return window['go']['main']['App']['GetGovernancePolicy']();
}

export function GetIdentityState() {
  return window['go']['main']['App']['GetIdentityState']();
}

export function GetMediaByCID(arg1) {
  return window['go']['main']['App']['GetMediaByCID'](arg1);
}

export function GetModerationLogs(arg1) {
  return window['go']['main']['App']['GetModerationLogs'](arg1);
}

export function GetModerationState() {
  return window['go']['main']['App']['GetModerationState']();
}

export function GetP2PStatus() {
  return window['go']['main']['App']['GetP2PStatus']();
}

export function GetPostBodyByCID(arg1) {
  return window['go']['main']['App']['GetPostBodyByCID'](arg1);
}

export function GetPostBodyByID(arg1) {
  return window['go']['main']['App']['GetPostBodyByID'](arg1);
}

export function GetPostMediaByID(arg1) {
  return window['go']['main']['App']['GetPostMediaByID'](arg1);
}

export function GetPrivateFeed() {
  return window['go']['main']['App']['GetPrivateFeed']();
}

export function GetProfile(arg1) {
  return window['go']['main']['App']['GetProfile'](arg1);
}

export function GetReleaseAlerts() {
  return window['go']['main']['App']['GetReleaseAlerts']();
}

export function GetReleaseMetrics() {
  return window['go']['main']['App']['GetReleaseMetrics']();
}

export function GetStorageUsage() {
  return window['go']['main']['App']['GetStorageUsage']();
}

export function GetSubs() {
  return window['go']['main']['App']['GetSubs']();
}

export function GetSubscribedSubs() {
  return window['go']['main']['App']['GetSubscribedSubs']();
}

export function GetTrustedAdmins() {
  return window['go']['main']['App']['GetTrustedAdmins']();
}

export function ImportIdentityFromMnemonic(arg1) {
  return window['go']['main']['App']['ImportIdentityFromMnemonic'](arg1);
}

export function LoadSavedIdentity() {
  return window['go']['main']['App']['LoadSavedIdentity']();
}

export function ProcessIncomingMessage(arg1) {
  return window['go']['main']['App']['ProcessIncomingMessage'](arg1);
}

export function PublishComment(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['PublishComment'](arg1, arg2, arg3, arg4);
}

export function PublishCommentUpvote(arg1, arg2, arg3) {
  return window['go']['main']['App']['PublishCommentUpvote'](arg1, arg2, arg3);
}

export function PublishCreateSub(arg1, arg2, arg3) {
  return window['go']['main']['App']['PublishCreateSub'](arg1, arg2, arg3);
}

export function PublishGovernancePolicy(arg1) {
  return window['go']['main']['App']['PublishGovernancePolicy'](arg1);
}

export function PublishPostStructured(arg1, arg2, arg3) {
  return window['go']['main']['App']['PublishPostStructured'](arg1, arg2, arg3);
}

export function PublishPostStructuredToSub(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['PublishPostStructuredToSub'](arg1, arg2, arg3, arg4);
}

export function PublishPostUpvote(arg1, arg2) {
  return window['go']['main']['App']['PublishPostUpvote'](arg1, arg2);
}

export function PublishPostWithImageToSub(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['PublishPostWithImageToSub'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function PublishProfileUpdate(arg1, arg2, arg3) {
  return window['go']['main']['App']['PublishProfileUpdate'](arg1, arg2, arg3);
}

export function PublishShadowBan(arg1, arg2, arg3) {
  return window['go']['main']['App']['PublishShadowBan'](arg1, arg2, arg3);
}

export function PublishUnban(arg1, arg2, arg3) {
  return window['go']['main']['App']['PublishUnban'](arg1, arg2, arg3);
}

export function SearchPosts(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchPosts'](arg1, arg2, arg3);
}

export function SearchSubs(arg1, arg2) {
  return window['go']['main']['App']['SearchSubs'](arg1, arg2);
}

export function SetDatabasePath(arg1) {
  return window['go']['main']['App']['SetDatabasePath'](arg1);
}

export function SetGovernancePolicy(arg1) {
  return window['go']['main']['App']['SetGovernancePolicy'](arg1);
}

export function SignMessage(arg1, arg2) {
  return window['go']['main']['App']['SignMessage'](arg1, arg2);
}

export function StartP2P(arg1, arg2) {
  return window['go']['main']['App']['StartP2P'](arg1, arg2);
}

export function StopP2P() {
  return window['go']['main']['App']['StopP2P']();
}

export function SubscribeSub(arg1) {
  return window['go']['main']['App']['SubscribeSub'](arg1);
}

export function TriggerAntiEntropySyncNow() {
  return window['go']['main']['App']['TriggerAntiEntropySyncNow']();
}

export function TriggerReleaseAlertEvaluationNow() {
  return window['go']['main']['App']['TriggerReleaseAlertEvaluationNow']();
}

export function UnsubscribeSub(arg1) {
  return window['go']['main']['App']['UnsubscribeSub'](arg1);
}

export function UpdateProfile(arg1, arg2) {
  return window['go']['main']['App']['UpdateProfile'](arg1, arg2);
}

export function UpvoteComment(arg1) {
  return window['go']['main']['App']['UpvoteComment'](arg1);
}

export function UpvotePost(arg1) {
  return window['go']['main']['App']['UpvotePost'](arg1);
}

export function VerifyMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['VerifyMessage'](arg1, arg2, arg3);
}
