// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddLocalPost(arg1:string,arg2:string,arg3:string):Promise<main.ForumMessage>;

export function AddTrustedAdmin(arg1:string,arg2:string):Promise<void>;

export function ApplyShadowBan(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ApplyUnban(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ConnectPeer(arg1:string):Promise<void>;

export function GenerateIdentity():Promise<main.Identity>;

export function GetFeed():Promise<Array<main.ForumMessage>>;

export function GetIdentityState():Promise<Array<main.IdentityState>>;

export function GetModerationState():Promise<Array<main.ModerationState>>;

export function GetP2PStatus():Promise<main.P2PStatus>;

export function GetPrivateFeed():Promise<Array<main.ForumMessage>>;

export function GetStorageUsage():Promise<main.StorageUsage>;

export function GetTrustedAdmins():Promise<Array<main.GovernanceAdmin>>;

export function ImportIdentityFromMnemonic(arg1:string):Promise<main.Identity>;

export function LoadSavedIdentity():Promise<main.Identity>;

export function ProcessIncomingMessage(arg1:Array<number>):Promise<void>;

export function PublishPost(arg1:string,arg2:string):Promise<void>;

export function PublishShadowBan(arg1:string,arg2:string,arg3:string):Promise<void>;

export function PublishUnban(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetDatabasePath(arg1:string):Promise<void>;

export function SignMessage(arg1:string,arg2:string):Promise<string>;

export function StartP2P(arg1:number,arg2:Array<string>):Promise<main.P2PStatus>;

export function StopP2P():Promise<void>;

export function VerifyMessage(arg1:string,arg2:string,arg3:string):Promise<boolean>;
