// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddFavorite(arg1:string):Promise<void>;

export function AddLocalComment(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.Comment>;

export function AddLocalPostStructured(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.ForumMessage>;

export function AddLocalPostStructuredToSub(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<main.ForumMessage>;

export function AddLocalPostWithImageToSub(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<main.ForumMessage>;

export function AddTrustedAdmin(arg1:string,arg2:string):Promise<void>;

export function ApplyShadowBan(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ApplyUnban(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ConnectPeer(arg1:string):Promise<void>;

export function CreateSub(arg1:string,arg2:string,arg3:string):Promise<main.Sub>;

export function GenerateIdentity():Promise<main.Identity>;

export function GetAntiEntropyStats():Promise<main.AntiEntropyStats>;

export function GetCommentsByPost(arg1:string):Promise<Array<main.Comment>>;

export function GetFavoritePostIDs():Promise<Array<string>>;

export function GetFavorites(arg1:number,arg2:string):Promise<main.PostIndexPage>;

export function GetFeed():Promise<Array<main.ForumMessage>>;

export function GetFeedBySub(arg1:string):Promise<Array<main.ForumMessage>>;

export function GetFeedBySubSorted(arg1:string,arg2:string):Promise<Array<main.ForumMessage>>;

export function GetFeedIndexBySubSorted(arg1:string,arg2:string):Promise<Array<main.PostIndex>>;

export function GetFeedStream(arg1:number):Promise<main.FeedStream>;

export function GetFeedStreamWithStrategy(arg1:number,arg2:string):Promise<main.FeedStream>;

export function GetGovernancePolicy():Promise<main.GovernancePolicy>;

export function GetIdentityState():Promise<Array<main.IdentityState>>;

export function GetMediaByCID(arg1:string):Promise<main.MediaBlob>;

export function GetModerationLogs(arg1:number):Promise<Array<main.ModerationLog>>;

export function GetModerationState():Promise<Array<main.ModerationState>>;

export function GetMyPosts(arg1:number,arg2:string):Promise<main.PostIndexPage>;

export function GetP2PConfig():Promise<main.P2PConfig>;

export function GetP2PStatus():Promise<main.P2PStatus>;

export function GetPostBodyByCID(arg1:string):Promise<main.PostBodyBlob>;

export function GetPostBodyByID(arg1:string):Promise<main.PostBodyBlob>;

export function GetPostIndexByID(arg1:string):Promise<main.PostIndex>;

export function GetPostMediaByID(arg1:string):Promise<main.MediaBlob>;

export function GetPrivateFeed():Promise<Array<main.ForumMessage>>;

export function GetProfile(arg1:string):Promise<main.Profile>;

export function GetReleaseAlerts():Promise<Array<main.ReleaseAlert>>;

export function GetReleaseMetrics():Promise<main.ReleaseMetrics>;

export function GetStorageUsage():Promise<main.StorageUsage>;

export function GetSubs():Promise<Array<main.Sub>>;

export function GetSubscribedSubs():Promise<Array<main.Sub>>;

export function GetTrustedAdmins():Promise<Array<main.GovernanceAdmin>>;

export function ImportIdentityFromMnemonic(arg1:string):Promise<main.Identity>;

export function IsFavorited(arg1:string):Promise<boolean>;

export function LoadSavedIdentity():Promise<main.Identity>;

export function ProcessIncomingMessage(arg1:Array<number>):Promise<void>;

export function PublishComment(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function PublishCommentUpvote(arg1:string,arg2:string,arg3:string):Promise<void>;

export function PublishCreateSub(arg1:string,arg2:string,arg3:string):Promise<void>;

export function PublishGovernancePolicy(arg1:boolean):Promise<void>;

export function PublishPostStructured(arg1:string,arg2:string,arg3:string):Promise<void>;

export function PublishPostStructuredToSub(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function PublishPostUpvote(arg1:string,arg2:string):Promise<void>;

export function PublishPostWithImageToSub(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;

export function PublishProfileUpdate(arg1:string,arg2:string,arg3:string):Promise<void>;

export function PublishShadowBan(arg1:string,arg2:string,arg3:string):Promise<void>;

export function PublishUnban(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RemoveFavorite(arg1:string):Promise<void>;

export function SaveP2PConfig(arg1:number,arg2:Array<string>,arg3:boolean):Promise<main.P2PConfig>;

export function SearchPosts(arg1:string,arg2:string,arg3:number):Promise<Array<main.ForumMessage>>;

export function SearchSubs(arg1:string,arg2:number):Promise<Array<main.Sub>>;

export function SetDatabasePath(arg1:string):Promise<void>;

export function SetGovernancePolicy(arg1:boolean):Promise<main.GovernancePolicy>;

export function SignMessage(arg1:string,arg2:string):Promise<string>;

export function StartP2P(arg1:number,arg2:Array<string>):Promise<main.P2PStatus>;

export function StopP2P():Promise<void>;

export function SubscribeSub(arg1:string):Promise<main.Sub>;

export function TriggerAntiEntropySyncNow():Promise<void>;

export function TriggerReleaseAlertEvaluationNow():Promise<Array<main.ReleaseAlert>>;

export function UnsubscribeSub(arg1:string):Promise<void>;

export function UpdateProfile(arg1:string,arg2:string):Promise<main.Profile>;

export function UpvoteComment(arg1:string):Promise<void>;

export function UpvotePost(arg1:string):Promise<void>;

export function VerifyMessage(arg1:string,arg2:string,arg3:string):Promise<boolean>;
